name: "Canvas Dev Stark"
install:
  - canvas
  - stark
config:
  actions:
    system.theme:
      simpleConfigUpdate:
        default: stark
    system.site:
      simpleConfigUpdate:
        page.front: /home
