name: "Canvas Dev OAuth"
install:
  - canvas
  - canvas_oauth
  - simple_oauth
  - consumers
config:
  import:
    canvas_oauth: "*"
  actions:
    simple_oauth.settings:
      simpleConfigUpdate:
        public_key: sites/default/files/public.key
        private_key: sites/default/files/private.key
