version: 1
name: canvas
source: https://git.drupalcode.org/project/canvas

channel:
  slack: C0BT3K7JXJ6

credentials:
  gitlab:
    username: balintbrews
    env: GITLAB_PAT

secrets: []

resources:
  cpu: 4
  memory: 8
  disk: 10
