#!/bin/bash

## Description: Drupal Canvas: Run PHPStan in the Canvas module's codebase.
## Usage: phpstan
## Example: "ddev phpstan"
## ExecRaw: true

cd "$DDEV_COMPOSER_ROOT/$DDEV_DOCROOT/modules/contrib/canvas" || exit 1

composer run phpstan
